AWSTemplateFormatVersion: 2010-09-09
Description: cleth stack

Parameters:
  VpcCidr:
    Description: IP range (CIDR notation) for this VPC
    Type: String

  PublicSubnetACidr:
    Description: IP range (CIDR notation) for the public subnet A in the first Availability Zone
    Type: String

  PublicSubnetBCidr:
    Description: IP range (CIDR notation) for the public subnet B in the second Availability Zone
    Type: String

  PrivateSubnetACidr:
    Description: IP range (CIDR notation) for the private subnet A in the first Availability Zone
    Type: String

  PrivateSubnetBCidr:
    Description: IP range (CIDR notation) for the private subnet B in the second Availability Zone
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true

  ElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref VPC

  AssociateVPC:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt VPC.AllocationId
      EIP: !Ref ElasticIp
      NetworkInterfaceId: !Ref EthereumNetworkInterface
  #
  # EthereumNetworkInterface:
  #   Type: AWS::EC2::NetworkInterface

  # Ec2Instance:
  #   Type: AWS::EC2::Instance

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnetACidr
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnetBCidr
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnetACidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnetBCidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
